//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sw2Rest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info
    {
        public int InfoID { get; set; }
        public int personneID { get; set; }
        public int masterID { get; set; }
        public int moduleID { get; set; }
        public string Semestre { get; set; }
        public string Note { get; set; }
        public string Etat { get; set; }
        public string Session { get; set; }
        public string Annee { get; set; }
    
        public virtual Master Master { get; set; }
        public virtual Module Module { get; set; }
        public virtual Personne Personne { get; set; }
    }
}
